# Trabajo Practico n4 - Introduccion a numpy.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: tp4_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

**Importaciones:**

In [10]:
import numpy as np
from random import randint

**Actividad 1:**: Crea un array de NumPy que contenga los números del 0 al 9. (Debes utilizar un metodo de numpy para su creacion.)

In [4]:
#todo: 

# Acá creamos un array con los números del a al 9 usando np.arange()
array_NumPy = np.arange(10)

print("El array da los siguientes resultados: ", array_NumPy)



El array da los siguientes resultados:  [0 1 2 3 4 5 6 7 8 9]


**Actividad 2:** Crea un array de 5 ceros, y luego cambia el tercer elemento (índice 2) para que sea 5. (Debes utilizar un metodo de numpy para su creacion.)

In [6]:
#todo:

# Hacemos un array de 5 ceros con np.zeros()
array_ceros = np.zeros(5)

# Se le cambia el valor en el índice 2 (el tercer elemento) a 5 :)
array_ceros[2] = 5

print("Array con un 5 en el índice 2", array_ceros)


Array con un 5 en el índice 2 [0. 0. 5. 0. 0.]


**Actividad 3:** Genera una matriz 3x3 de números aleatorios entre 0 y 1.

In [8]:
#todo: 
# Hacemos una matriz de 3x3 con números aleatorios entre 0 y 1

matriz_random = np.random.uniform(low=0.0001, high=0.9999, size=(3, 3))

# Forzamos que los valores estén en un rango como (0.0001, 0.9999), porque dice entre 0 y 1 :) 

print("Matriz 3x3 con números entre el 0 y el 1 (excluyendo al 0 y 1):", matriz_random)


Matriz 3x3 con números entre el 0 y el 1 (excluyendo al 0 y 1): [[0.17228128 0.8050939  0.45302625]
 [0.85384033 0.13597909 0.02536525]
 [0.52278277 0.57703116 0.49922242]]


**Actividad 4:** Dado el siguiente array `arr = np.array([10, 20, 30, 40, 50])`
1. Suma 5 a cada elemento.
2. Multiplica todo por un numero aleatorio (utiliza el modulo random para generarlo.)

In [13]:
#todo:
import random 
# no me tomaba el random.uniform() así que lo importé de nuevo

arr = np.array([10, 20, 30, 40, 50])

# Se Suman 5 a cada elemento
arr_5 = arr + 5

# Se saca un número aleatorio entre el 1 y el 10 para multiplicarlo por el array
numero_random = random.uniform(1, 10)

arr_multi = arr_5 * numero_random

print("Array original + 5:", arr_5)
print("El Array multiplicado por: ", numero_random," es ", arr_multi)



Array original + 5: [15 25 35 45 55]
El Array multiplicado por:  1.8990853895569346  es  [ 28.48628084  47.47713474  66.46798863  85.45884253 104.44969643]


**Actividad 5:** Crea una matriz identidad de tamaño 4x4 (unos en la diagonal principal y ceros en el resto).

In [18]:
#todo:

# Hacemos una matriz identidad de 4x4 usando np.eye(), tenia pensado usar identity() pero no me tomaba el import (?)
matriz_id = np.eye(4)

print("Matriz identidad 4x4:", matriz_id)


Matriz identidad 4x4: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Actividad 6:** Crea un array que comience en 0 hasta el 20, pero que solo tenga numeros pares yu luego realiza las 4 operaciones basicas. (suma, resta, multiplicacion, division).

In [21]:
#todo: 

import numpy as np

# Hacemos un array de números entre 0 y 20, usando un booleano en mi caso
array_par = np.array([i for i in range(21) if i % 2 == 0])

# Le pedimos un número al usuario y lo convertimos a entero
numero = int(input("Ingrese un número para realizar operaciones con el array: "))

suma = array_par + numero
resta = array_par - numero
multiplicacion = array_par * numero
division = array_par / numero

# Se muestran los resultados
print("Array original:", array_par)
print("Suma :".format(numero), suma)
print("Resta :".format(numero), resta)
print("Multiplicación :".format(numero), multiplicacion)
print("División :".format(numero), division)




Array original: [ 0  2  4  6  8 10 12 14 16 18 20]
Suma : [ 3  5  7  9 11 13 15 17 19 21 23]
Resta : [-3 -1  1  3  5  7  9 11 13 15 17]
Multiplicación : [ 0  6 12 18 24 30 36 42 48 54 60]
División : [0.         0.66666667 1.33333333 2.         2.66666667 3.33333333
 4.         4.66666667 5.33333333 6.         6.66666667]
